[package]
name = "metashrew-oom-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
metashrew-core = { path = "../../crates/metashrew-core" }
metashrew-support = { path = "../../crates/metashrew-support" }
bitcoin = "0.29.2"