#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, run the following command:
#
#   ln -s ../../scripts/pre-commit .git/hooks/pre-commit

# Format all staged Rust files
cargo fmt --all